JuniorTestApp/Models/Item.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace JuniorTestApp.Models
{
    public class Item
    {
        public int Id { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string SKU { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string Brand { get; set; }
        
        [Range(0, Single.MaxValue)]
        public Single? Price { get; set; }
        [Range(0, Single.MaxValue)]
        public Single? Weight { get; set; }
        public string Feature { get; set; }
        public string ProductParameter { get; set; }
        public string ColumnNames { get; set; }
    }

    public class ItemContext : DbContext
    {
        public DbSet<Item> Items { get; set; }
    }
}

JuniorTestApp/Controllers/HomeController.cs
using JuniorTestApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JuniorTestApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

JuniorTestApp/Controllers/ItemsController.cs
using JuniorTestApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.IO;
using System.Diagnostics;
using System.Data.SqlClient;
using PagedList;
using System.Data.Entity.Validation;
using System.Globalization;

namespace JuniorTestApp.Controllers
{
    public class ItemsController : Controller
    {
        ItemContext db = new ItemContext();

        // GET: Items
        public ActionResult Index(int? page)
        {
            int pageSize = 50;
            int pageNumber = (page ?? 1);
            return View(db.Items.OrderBy(i => i.SKU).ToPagedList(pageNumber, pageSize));
        }

        // POST: Items/Import
        [HttpPost]
        public ActionResult Import(HttpPostedFileBase csvFile)
        {
            string filePath = String.Empty;
            if (csvFile != null)
            {
                string pathToDir = Server.MapPath("~/Uploads/");
                if(!Directory.Exists(pathToDir))
                {
                    Directory.CreateDirectory(pathToDir);
                }

                filePath = pathToDir + Path.GetFileName(csvFile.FileName);
                csvFile.SaveAs(filePath);

                string csvData = System.IO.File.ReadAllText(filePath);
                ViewBag.csvData = csvData;
                return View();
            }
            Debug.WriteLine("Csv file is null!");
            return View();
        }

        // POST: Items/Mapping
        [HttpPost]
        public ActionResult Mapping(string csvData, FormCollection collection)
        {
            ItemContext itemContex = new ItemContext();
            List<Item> items = new List<Item>();

            string[] columns = collection[2].Split(',');
            string[] parameters = collection[3].Split(',');
            
            if (columns.Length != parameters.Length)
            {
                string error = columns.Length.ToString() + " " + parameters.Length.ToString();

                return Redirect("/Index");
            }            

            foreach (string row in csvData.Split('\n').Skip(1))
            {
                if(!String.IsNullOrEmpty(row))
                {
                    Item item = new Item();
                    string features = String.Empty;
                    string productParameters = String.Empty;
                    string columnNames = String.Empty;

                    for (int i = 0; i < row.Split(',').Count(); i++)
                    {
                        string field = row.Split(',').ElementAt(i);

                        if (parameters[i] != "Ignore")
                        {
                            columnNames += columns[i] + "|";
                            if(!String.IsNullOrEmpty(field))
                            {
                                switch (parameters[i])
                                {
                                    case "SKU":
                                        try
                                        {
                                            item.SKU = field;
                                        }
                                        catch (Exception ex)
                                        {
                                            Debug.Write(ex.Message + "\n");
                                        }
                                        break;
                                    case "Brand":
                                        try
                                        {
                                            item.Brand = field;
                                        }
                                        catch (Exception ex)
                                        {
                                            Debug.Write(ex.Message + "\n");
                                        }
                                        break;
                                    case "Price":
                                        try
                                        {
                                            item.Price = float.Parse(field, CultureInfo.InvariantCulture.NumberFormat);
                                        }
                                        catch (Exception ex)
                                        {
                                            Debug.Write(ex.Message + "\n");
                                        }
                                        break;
                                    case "Weight":
                                        try
                                        {
                                            item.Weight = float.Parse(field, CultureInfo.InvariantCulture.NumberFormat);
                                        }
                                        catch (Exception ex)
                                        {
                                            Debug.Write(ex.Message + "\n");
                                        }
                                        break;
                                    case "Feature":
                                        features += field + "|";
                                        break;
                                    case "Product parameter":
                                        productParameters += field + "|";
                                        break;
                                    default:
                                        Debug.Write(parameters[i] + "\n");
                                        break;
                                }
                            }
                        }
                    }

                    item.ColumnNames = columnNames;
                    item.Feature = features;
                    item.ProductParameter = productParameters;

                    itemContex.Items.Add(item);
                }
            }

            try
            {
                itemContex.SaveChanges();
            }
            catch (DbEntityValidationException ex)
            {
                foreach (DbEntityValidationResult validationError in ex.EntityValidationErrors)
                {
                    Response.Write("Object: " + validationError.Entry.Entity.ToString());
                    Response.Write("");
                    foreach (DbValidationError err in validationError.ValidationErrors)
                    {
                        Response.Write(err.ErrorMessage + "");
                    }
                }
            }

            return RedirectToAction("Index");
        }
        
    }
}

JuniorTestApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

JuniorTestApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

JuniorTestApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Главная";
}

<div class="row">
    <div class="col-md-12">
        <div class="jumbotron" style="margin-top: 2rem;">
            @using (Html.BeginForm("Import", "Items", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <p id="fileUploadingError" style="color:red;margin-bottom: 1rem;"></p>
                <div class="form-inline">
                    <input id="csvFileBtn" name="csvFile" type="file" accept=".csv" />
                    <input id="submitFileImportBtn" type="submit" class="btn btn-primary" style="margin-left:1rem;" />
                </div>
            }
        </div>
        
    </div>
</div>

JuniorTestApp/Views/Items/Import.cshtml
@{
    ViewBag.Title = "Import";
    string csvData = ViewBag.csvData;

    string findExampleValues(int columnIndex)
    {
        List<string> exampleValues = new List<string>();
        string columns = csvData.Split('\n').Skip(0).Take(1).ElementAt(0);

        foreach (string row in csvData.Split('\n').Skip(1))
        {
            if(!string.IsNullOrEmpty(row))
            {
                string exampleValue = row.Split(',')[columnIndex];

                if (exampleValues.Count < 4 && !String.IsNullOrEmpty(exampleValue) && !exampleValues.Exists(element => element == exampleValue))
                {
                    exampleValues.Add(exampleValue);
                }
                else if(exampleValues.Count == 4)
                {
                    exampleValues.Add("...");
                }
            }
        }

        string values = String.Empty;
        for(int i = 0; i < exampleValues.Count; i++)
        {
            values += exampleValues[i];
            if (i != exampleValues.Count - 1)
            {
                values += " / ";
            }
        }

        return values;
    }
}

<div class="row" style="margin-top:4rem;">
    <div class="col-12">
        @using (Html.BeginForm("Mapping", "Items", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken();
            <input name="csvData" type="hidden" value="@csvData" />

            <table class="table">
                <thead class="thead-inverse" style="font-weight: bold;">
                    <tr>
                        <th>Колонка</th>
                        <th>Параметр</th>
                        <th>Примеры значений</th>
                        <th>Ошибки данных</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        string row = csvData.Split('\n').Skip(0).Take(1).ElementAt(0);
                        for (int i = 0; i < row.Split(',').Count(); i++)
                        {
                            <tr>
                                <input name="columnName" type="hidden" value="@row.Split(',')[i]" />
                                <td>@row.Split(',')[i]</td>
                                <td>
                                    <select id="@row.Split(',')[i]" name="parameterName" onchange="checkParameters(this.value)">
                                        <option value="NoMapped" selected>NoMapped</option>
                                        <option value="SKU">SKU</option>
                                        <option value="Brand">Brand</option>
                                        <option value="Price">Price</option>
                                        <option value="Weight">Weight</option>
                                        <option value="Feature">Feature</option>
                                        <option value="Product parameter">Product parameter</option>
                                        <option value="Ignore">Ignore</option>
                                    </select>
                                </td>
                                <td>@findExampleValues(i)</td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
            <div class="float-right">
                <span id="error" style="color: red;"></span>
                <input id="map" type="submit" value="Ок" class="btn btn-primary" />
                <button role="link" class="btn btn-secondary">Отмена</button>
            </div>
        }
    </div>
</div>

JuniorTestApp/Views/Items/Index.cshtml
@model PagedList.IPagedList<JuniorTestApp.Models.Item>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
}
<table class="table">
    <thead>
        <tr>
            @if (Model.Count > 0)
            {
                foreach (string column in Model.First().ColumnNames.Split('|'))
                {
                    <th>
                        @column
                    </th>
                }
            }
            else
            {
                <p>There is no records in database</p>
            }

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SKU)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Brand)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Weight)
                </td>
                @foreach (string val in item.Feature.Split('|'))
                {
                    if (!String.IsNullOrEmpty(val))
                    {
                        <td>
                            @val
                        </td>
                    }

                }
                @foreach (string val in item.ProductParameter.Split('|'))
                {
                    if (!String.IsNullOrEmpty(val))
                    {
                        <td>
                            @val
                        </td>
                    }
                }
            </tr>
        }
    </tbody>
</table>

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

JuniorTestApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

    <script>
        $(document).ready(function () {
            $("#submitFileImportBtn").attr("disabled", true);

            $("#csvFileBtn").change(function () {
                if ($("#csvFileBtn").val())
                {
                    var filename = $("#csvFileBtn").val();
                    
                    var extension = filename.replace(/^.*\./, '');

                    if (extension == filename) {
                        extension = '';
                    }
                    else {
                        extension = extension.toLowerCase();
                    }

                    if (extension == "csv") {
                        $("#fileUploadingError").text("");
                        $("#submitFileImportBtn").attr("disabled", false);
                    }
                    else {
                        $("#fileUploadingError").text("Пожалуйста, выберите файл формата .csv и повторите попытку");
                    }
                }
            });
        });
    </script>

    <script>
        var values;
        var isDisabled = false;

        $(document).ready(function () {
            values = $("select option:selected").map(function () { return $(this).val() }).get();
            $("#map").attr("disabled", true);
        });

        function checkParameters(optionValue)
        {
            values = $("select option:selected").map(function () { return $(this).val() }).get();

            if (jQuery.inArray("NoMapped", values) !== -1) // -1 == Not Found
            {
                console.log("NoMapped found");
                isDisabled = true;
                $("#error").text("Пожалуйста, настройте все поля");
            }
            else {
                console.log("NoMapped not found");
                isDisabled = false;
                $("#error").text("");
            }

            $("#map").attr("disabled", isDisabled);
        } 
    </script>

</head>
<body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        @Html.ActionLink("MapTool", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    @Html.ActionLink("Список продукции", "Index", "Items", new { @class = "nav-link" })
                </li>
            </ul>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>